[package]
name = "hexify-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
serde = { version = "1.0.192", features = ["serde_derive"] }
shuttle-axum = "0.34.0"
shuttle-runtime = "0.34.0"
thiserror = "1.0.50"
tokio = "1.28.2"
tracing = "0.1.40"
